Final touches
wacoo/smart-budget-ror-capstone pull request #1
Opened 2023-11-30 21:11 UTC by wacoo

- Add migrations, models, and controllers for group, expense, group_expense
- Add views for group, expense, group_expense, splash
- Add model, controller, and integration tests
- Add project presentation
- Fix linter errors

2023-11-30 22:28 UTC, Qoosim commented
Hi @wacoo, you should not have submitted your project when you know that you're not fully done with the project. You are making new commits every now and then which has made the review to be difficult for me to give you feedback. Please, stop commiting to this PR again untill I am done with the review. Thanks

2023-11-30 22:32 UTC, wacoo commented
Sorry, I forgot I am working on the same branch. I will not change it again.

2023-11-30 22:33 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @wacoo, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  Implemented some project requirements. :heavy_check_mark: 
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-30 22:33 UTC, Qoosim commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] Great job making a video highlighting the features of your application. However, there's a requirement that is missing from the video. It is required that your video should include highlight about a piece of the code you find interesting or you're proud of making. That is not yet included in your video. Kindly make a new video that includes that requirement.

![piece-of-code](https://github.com/wacoo/smart-budget-ror-capstone/assets/26597432/fd7b2e35-02cf-42ae-b548-595e9ec7c40d)

2023-11-30 22:33 UTC, Qoosim commented on spec/features/expense/expense_integration_spec.rb
> +end
- [ ]  Some tests of your application are failing at this moment. Kindly look at them and fix. 

![failed-test-1](https://github.com/wacoo/smart-budget-ror-capstone/assets/26597432/5ce6e711-87f5-4cb5-b3b1-a5eaf5872b73)


![failed-test-2](https://github.com/wacoo/smart-budget-ror-capstone/assets/26597432/6b43b152-0faa-4d8a-b798-e534f03d805b)

2023-11-30 23:45 UTC, Munsa1 requested changes
Hi @wacoo @, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-11-30 23:45 UTC, Munsa1 commented on spec/features/expense/expense_integration_spec.rb
> +      io: File.open(Rails.root.join('app', 'assets', 'images', 'mo.png')),
- [ ] Good job for making the required changes however, we still have some failing testcases, Kindly resolve these issues as tests ensure our code works as expected.

![image](https://github.com/wacoo/smart-budget-ror-capstone/assets/81932478/dbb766d4-0e08-4df8-ac67-b95129046098)

Context
It looks like you are encountering an error related to the version of ChromeDriver in your Selenium configuration for testing. The error indicates that the specified version, 119.0.6045, is not found on the ChromeDriver storage.

2023-12-01 05:15 UTC, wacoo commented on spec/features/expense/expense_integration_spec.rb
> +      io: File.open(Rails.root.join('app', 'assets', 'images', 'mo.png')),
My laptop is Chromebook. Selenium doesn't detect the existing Chrome browser on my laptop or any Chrome browser that I install. The tests fails trying to load a browser. That's why I use rack_test which part of the same gem as selenium, but it doesn't load a browser. The tests are the same. However, you need to test each test type individually for it to work. Here are the same tests as the above: 
![image](https://github.com/wacoo/smart-budget-ror-capstone/assets/9458141/62c74fd2-df0c-4297-8619-eb9887594b00)

2023-12-01 05:31 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Wonde,  

**RoR capstone project** is complete! 🏁 Great job, Congratulations!  🎉💯🌟 

## Highlights 🎯 
🎲 Test cases are passing!
🎲 ReadMe looks great!

Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-01 06:10 UTC, merged